kind: Deployment
apiVersion: apps/v1
metadata:
   name: department-service
spec:
   replicas: 2
   selector:
      matchLabels:
         app: department-service
   template:
      metadata:
         name: department-service
         labels:
            app: department-service
      spec:
         containers:
         -  name: department-service
            image: qualitto007/department-service:latest
            imagePullPolicy: Always
            ports:
            -  containerPort: 9091
---
kind: Service
apiVersion: v1
metadata:
   name: department-service-k8srv
   labels:
      app: department-service-k8srv
spec:
   type: NodePort
   ports:
   -  nodePort: 30003
      port: 9091
      targetPort: 9091
   selector:
      app: department-service