kind: Deployment
apiVersion: apps/v1
metadata:
   name: department-service
spec:
   replicas: 2
   selector:
      matchLabels:
         app: department-service
   template:
      metadata:
         name: department-service
         labels:
            app: department-service
      spec:
         containers:
         -  name: department-service
            image: qualitto007/department-service:latest
            imagePullPolicy: Always
            ports:
            -  containerPort: 9091
---
kind: Service
apiVersion: v1
metadata:
   name: department-service-k8srv
   labels:
      app: department-service-k8srv
spec:
   ports:
    - port: 9091
   selector:
      app: department-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qualitto-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: "qualitto.com"
    http:
      paths:
        - path: /departments
          pathType: Prefix
          backend:
            service:
              name: config-server-k8srv
              port: 
                number: 9091